name: Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      max-parallel: 1
      matrix:
        ruby:
          - '3.1.4'
          - '3.2.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        TEST_HTTP_URL: ${{ secrets.TEST_HTTP_URL }}
        TEST_PG_URL: ${{ secrets.TEST_PG_URL }}
        TEST_MYSQL_URL: ${{ secrets.TEST_MYSQL_URL }}
        ENABLE_EXTERNAL_TESTS: ${{ secrets.ENABLE_EXTERNAL_TESTS }}
      run: bundle exec rake
  docs:
    runs-on: ubuntu-latest
    name: Validate docs
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - name: Run YARD
      run: bundle exec yardoc --fail-on-warning
  cli:
    runs-on: ubuntu-latest
    name: Test CLI
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    - name: Build the gem
      run: gem build -o rage-local.gem && gem install rage-local.gem --no-document
    - name: Create a project
      run: rage new my_app
    - name: Start the server
      working-directory: ./my_app
      run: bundle install && bundle exec rage s&
    - name: Test the default route
      run: curl --fail http://localhost:3000
    - name: Run the routes task
      working-directory: ./my_app
      run: bundle exec rage routes
