name: Tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      max-parallel: 1
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        TEST_HTTP_URL: ${{ secrets.TEST_HTTP_URL }}
        TEST_PG_URL: ${{ secrets.TEST_PG_URL }}
        TEST_MYSQL_URL: ${{ secrets.TEST_MYSQL_URL }}
        TEST_REDIS_URL: ${{ secrets.TEST_REDIS_URL }}
        ENABLE_EXTERNAL_TESTS: ${{ secrets.ENABLE_EXTERNAL_TESTS }}
      run: bundle exec rake
  linter:
    runs-on: ubuntu-latest
    name: Code Style
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run Linter
      run: bundle exec rubocop
  docs:
    runs-on: ubuntu-latest
    name: Docs
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run YARD
      run: bundle exec yardoc --fail-on-warning
  cli:
    runs-on: ubuntu-latest
    name: CLI
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Build the gem
      run: gem build -o rage-local.gem && gem install rage-local.gem --no-document
    - name: Create a project
      run: rage new my_app
    - name: Start the server
      working-directory: ./my_app
      run: bundle install && bundle exec rage s&
    - name: Test the default route
      run: curl --fail http://localhost:3000
    - name: Run the routes task
      working-directory: ./my_app
      run: bundle exec rage routes
    - name: Add a Rake task
      working-directory: ./my_app
      run: printf "desc \"Prints From Rake\"\nnamespace :hello do\ntask :print do\nend\nend" > lib/tasks/hello.rake
    - name: Check available Rake tasks
      working-directory: ./my_app
      run: bundle exec rake --tasks | grep "rake hello:print"
    - name: Run the Rake task
      working-directory: ./my_app
      run: bundle exec rake hello:print
  cli-d:
    runs-on: ubuntu-latest
    name: CLI DB
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Build the gem
      run: gem build -o rage-local.gem && gem install rage-local.gem --no-document
    - name: Create a project
      run: rage new my_app -d sqlite3
    - name: Bundle install
      working-directory: ./my_app
      run: bundle
    - name: List available tasks
      working-directory: ./my_app
      shell: 'script -q -e -c "bash {0}"'
      run: bundle exec rage --tasks
    - name: Create a database
      working-directory: ./my_app
      run: bundle exec rage db:create
    - name: Create a model
      working-directory: ./my_app
      run: bundle exec rage g model User
    - name: Migrate
      working-directory: ./my_app
      run: bundle exec rage db:migrate
    - name: Start the server
      working-directory: ./my_app
      run: bundle install && bundle exec rage s&
    - name: Test the default route
      run: curl --fail http://localhost:3000

